test_symptoms = [
    ["chest pain", "radiates to arm or jaw", "sweating"],
    ["palpitations", "anxiety", "mild sweating"],
    ["mild headache", "slight fatigue", "loss of appetite"],
    ["sudden dizziness", "blurred vision", "high blood pressure"],
    ["runny nose", "mild sore throat", "sneezing"],
    ["shortness of breath", "fatigue", "slight dizziness"],
    ["mild stomach discomfort", "bloating", "occasional nausea"],
    ["severe abdominal pain", "vomiting blood"],
    ["persistent cough", "chest tightness", "low-grade fever"],
    ["back pain", "numbness in legs", "difficulty walking"],
    ["swollen ankle", "pain while walking", "redness"],
    ["itchy eyes", "watery eyes", "sneezing"],
    ["frequent urination", "increased thirst", "fatigue"],
    ["loss of smell", "loss of taste", "mild headache"],
    ["confusion", "slurred speech", "facial droop"],
    ["joint pain", "stiffness in morning", "swelling"],
    ["rash", "fever", "joint pain"],
    ["vomiting", "diarrhea", "dehydration"],
    ["severe headache", "sensitivity to light", "nausea"],
    ["chest tightness", "shortness of breath", "wheezing"],
    ["persistent fatigue", "weight loss", "night sweats"],
    ["abdominal cramping", "diarrhea", "blood in stool"],
    ["numbness in hand", "tingling fingers", "weak grip"],
    ["sudden weakness", "drooping eyelid", "slurred speech"],
    ["rapid heartbeat", "dizziness", "fainting"],
    ["severe lower back pain", "numb legs", "loss of bladder control"],
    ["persistent cough", "blood in sputum", "weight loss"],
    ["fever", "stiff neck", "headache"],
    ["difficulty breathing", "wheezing", "chest tightness"],
    ["abdominal swelling", "yellow skin", "dark urine"],
    ["blurred vision", "headache", "eye pain"],
    ["mild fever", "fatigue", "muscle aches"],
    ["sore throat", "fever", "swollen lymph nodes"],
    ["frequent urination", "burning sensation", "abdominal pain"],
    ["tremors", "difficulty speaking", "stiff muscles"],
    ["chest pain during exertion", "shortness of breath", "fatigue"],
    ["sudden severe headache", "vomiting", "confusion"],
    ["persistent diarrhea", "weight loss", "fatigue"],
    ["rash spreading rapidly", "fever", "chills"],
    ["swollen feet", "shortness of breath", "fatigue"],
    ["rapid heartbeat", "chest discomfort", "dizziness"],
    ["joint swelling", "morning stiffness", "fatigue"],
    ["loss of balance", "dizziness", "headache"],
    ["sudden severe abdominal pain", "vomiting", "diarrhea"],
    ["nausea", "vomiting", "abdominal bloating"],
    ["shortness of breath at rest", "confusion", "cyanosis"],
    ["persistent cough", "chest pain", "night sweats"],
    ["blurred vision", "dry eyes", "headache"],
    ["palpitations", "chest discomfort", "anxiety"],
    ["persistent mild fever", "fatigue", "loss of appetite"],
    ["sore throat", "mild fever", "runny nose"],
    ["severe joint pain", "swelling", "redness"]
]
