# Generated by Django 5.1.5 on 2026-01-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalsummary',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
