# Generated by Django 5.1.5 on 2026-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_clinicalsummary_pdf_alter_questionanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalsummary',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='File/'),
        ),
    ]
