# Generated by Django 4.2.27 on 2026-01-09 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(help_text='Patient age in years', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1)),
                ('is_pregnant', models.BooleanField(default=False, help_text='Is the patient pregnant? (for reference range adjustment)')),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='lab_reports/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='lab_analyzer.patient')),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('findings', models.JSONField(default=dict, help_text='Structured JSON containing all analysis findings')),
                ('clinical_summary', models.TextField(blank=True, null=True)),
                ('critical_flags', models.IntegerField(default=0, help_text='Number of critical findings')),
                ('has_critical', models.BooleanField(db_index=True, default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('lab_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='lab_analyzer.labreport')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['status', '-uploaded_at'], name='lab_analyze_status_fd61e3_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['patient', '-uploaded_at'], name='lab_analyze_patient_918eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['-generated_at'], name='lab_analyze_generat_793338_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['has_critical', '-generated_at'], name='lab_analyze_has_cri_221ab0_idx'),
        ),
    ]
