# Generated by Django 4.2.27 on 2026-01-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ur', 'Urdu (اردو)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)'), ('ps', 'Pashto (پښتو)'), ('sd', 'Sindhi (سنڌي)')], default='en', help_text='Preferred language for summary and explanations', max_length=2),
        ),
    ]
