# Generated by Django 5.2.4 on 2026-01-10 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='english', max_length=20)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('conditions', models.TextField(help_text='e.g., CKD Stage 3, Diabetes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=50)),
                ('raw_analysis', models.TextField()),
                ('soap_note', models.TextField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medication_interaction.medicationsession')),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=255)),
                ('is_new', models.BooleanField(default=False, help_text='Is this the drug they want to start?')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medication_interaction.medicationsession')),
            ],
        ),
    ]
